apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.13.2
    helm:
      values: |
        clusterName: andy-cluster-xplane-eks-cluster
        region: ap-southeast-1

        replicaCount: 1

        # Toleration for Karpenter infra nodepool
        tolerations:
        - key: "karpenter.sh/nodepool"
          operator: "Equal"
          value: "infra"
          effect: "NoSchedule"

        # Development-specific configurations for Crossplane EKS cluster
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 512Mi

        # Enable webhook for development
        enableCertManager: true

        # Development logging
        logLevel: info

        # Crossplane EKS specific settings
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/AWSLoadBalancerControllerRole"
        
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: aws-load-balancer-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 