apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
spec:
  source:
    helm:
      values: |
        # Cluster-specific configuration for andy-cluster-xplane-eks-cluster
        clusterName: andy-cluster-xplane-eks-cluster
        
        # Development settings
        logLevel: info
        
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 512Mi
        
        # Crossplane EKS specific settings
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/AWSLoadBalancerControllerRole" 