apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-cluster-prod-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/xawei/learning
    targetRevision: main
    path: argocd/myprj/base-components
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true        # ✅ Automatically remove resources not in Git
      selfHeal: true     # ✅ Automatically sync when Git changes
      allowEmpty: false  # ✅ Prevent accidental deletion of all apps
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground  # ✅ Ensure proper cleanup order
      - PruneLast=true                     # ✅ Prune after sync, not before
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
