{{- if .Values.velero.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 10.0.10
    helm:
      values: |
        serviceAccount:
          server:
            create: true
            annotations:
              eks.amazonaws.com/role-arn: {{ .Values.velero.serviceAccount.roleARN | quote }}
        credentials:
          useSecret: false
        configuration:
          provider: {{ .Values.velero.configuration.provider | quote }}
          backupStorageLocation:
            name: default
            bucket: {{ .Values.velero.configuration.bucket | quote }}
            config:
              region: {{ .Values.velero.configuration.region | quote }}
          volumeSnapshotLocation:
            name: default
            config:
              region: {{ .Values.velero.configuration.region | quote }}
        initContainers:
        - name: velero-plugin-for-aws
          image: {{ index .Values.velero.plugins 0 "image" }}
          volumeMounts:
            - mountPath: /target
              name: plugins
        tolerations:
        {{- toYaml .Values.velero.tolerations | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }} 