apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-policy-agent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://open-policy-agent.github.io/gatekeeper/charts
    chart: gatekeeper
    targetRevision: 3.16.3
    helm:
      values: |
        # OPA Gatekeeper configuration
        replicas: 1
        
        # Audit configuration
        audit:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        
        # Controller manager configuration
        controllerManager:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        
        # Webhook configuration
        webhook:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        
        # Image configuration
        image:
          pullPolicy: IfNotPresent
        
        # RBAC
        rbac:
          create: true
        
        # Service account
        serviceAccount:
          create: true
        
        # Security context
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 999
          runAsNonRoot: true
          runAsUser: 1000
        
        # Pod security context
        podSecurityContext:
          fsGroup: 999
          supplementalGroups:
            - 999
        
        # Node selector
        nodeSelector: {}
        
        # Tolerations
        tolerations: []
        
        # Affinity rules
        affinity: {}
        
        # Pod disruption budget
        podDisruptionBudget:
          maxUnavailable: 1
        
        # Metrics and monitoring
        metrics:
          enabled: true
        
        # Mutation webhook
        mutations:
          enable: true
        
        # Validation webhook
        validatingAdmissionWebhook:
          failurePolicy: Fail
          timeoutSeconds: 10
        
        # Mutating admission webhook  
        mutatingAdmissionWebhook:
          failurePolicy: Fail
          timeoutSeconds: 10
        
        # External data provider
        externalDataProvider:
          enable: false
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 