apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.27.0
    helm:
      values: |
        # Simple Prometheus configuration for Kind cluster
        server:
          replicaCount: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          persistentVolume:
            enabled: false
          service:
            type: ClusterIP
        
        # Disable components not needed for simple setup
        alertmanager:
          enabled: false
        
        prometheus-node-exporter:
          enabled: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
        
        prometheus-pushgateway:
          enabled: false
        
        kube-state-metrics:
          enabled: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
        
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          fsGroup: 65534
        
        # Service account
        serviceAccounts:
          server:
            create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 