apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 5.2.2
    helm:
      values: |
        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: velero-backups
              config:
                region: us-west-2
          volumeSnapshotLocation:
            - name: default
              provider: aws
              config:
                region: us-west-2
          defaultBackupTTL: 720h
          logLevel: info
        
        serviceAccount:
          server:
            create: true
        
        rbac:
          create: true
          clusterAdministrator: true
        
        credentials:
          useSecret: false
        
        deployNodeAgent: false
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 