apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 5.2.2
    helm:
      values: |
        # Minimal Velero configuration for Kind cluster
        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: velero-backups
              config:
                region: us-west-2
                s3ForcePathStyle: false
          volumeSnapshotLocation:
            - name: default  
              provider: aws
              config:
                region: us-west-2
          defaultBackupTTL: 720h
          logLevel: info
        
        # Service account  
        serviceAccount:
          server:
            create: true
        
        # RBAC
        rbac:
          create: true
          clusterAdministrator: true
        
        # Resources
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        
        # Security context
        securityContext:
          fsGroup: 65534
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
        
        # Credentials
        credentials:
          useSecret: false
        
        # Node agent (updated configuration)
        deployNodeAgent: true
        nodeAgent:
          podVolumePath: /var/lib/kubelet/pods
          privileged: false
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            runAsUser: 0
            privileged: false
        
        # Init containers for AWS plugin
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.8.2
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 