apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 5.2.2
    helm:
      values: |
        # Velero configuration
        configuration:
          # Backup storage location
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: velero-backups
              config:
                region: us-west-2
                # For S3-compatible storage
                s3ForcePathStyle: false
                # s3Url: http://minio:9000
          
          # Volume snapshot location  
          volumeSnapshotLocation:
            - name: default
              provider: aws
              config:
                region: us-west-2
          
          # Default backup TTL (720h = 30 days)
          defaultBackupTTL: 720h
          
          # Features
          features: ""
          
          # Log level
          logLevel: info
          
          # Log format
          logFormat: text

        # Resource settings
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

        # Node selection
        nodeSelector: {}
        tolerations: []
        affinity: {}

        # Security context
        securityContext:
          fsGroup: 65534
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534

        # Pod security context
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
          fsGroup: 65534

        # Service account
        serviceAccount:
          server:
            create: true
            name: ""
            annotations: {}
            labels: {}

        # RBAC
        rbac:
          create: true
          clusterAdministrator: true

        # Credentials (for AWS, you'll need to provide these)
        credentials:
          useSecret: false
          # name: cloud-credentials
          # existingSecret: 
          # secretContents: {}

        # Backup schedules (examples)
        schedules:
          daily-backup:
            disabled: false
            labels:
              myenv: daily
            annotations:
              myenv: daily  
            schedule: "0 1 * * *"
            useOwnerReferencesInBackup: false
            template:
              ttl: "240h"  # 10 days
              includedNamespaces:
                - "*"
              excludedNamespaces:
                - kube-system
              includedResources:
                - "*"
              excludedResources: []

        # Init containers
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.8.2
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins

        # Metrics
        metrics:
          enabled: true
          scrapeInterval: 30s
          scrapeTimeout: 10s
          service:
            annotations: {}
            labels: {}
          podAnnotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "8085"
            prometheus.io/path: "/metrics"

        # Deployment settings
        deployRestic: true
        restic:
          podVolumePath: /var/lib/kubelet/pods
          privileged: false
          priorityClassName: ""
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          tolerations: []
          securityContext:
            runAsUser: 0
            privileged: false
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 