apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
spec:
  source:
    helm:
      values: |
        # Cluster-specific configuration for cluster-c
        clusterName: cluster-c
        
        # Custom settings for cluster-c
        logLevel: info
        replicaCount: 1
        
        resources:
          requests:
            cpu: 150m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi 