apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-kind-eksac-dev-appset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - git:
      repoURL: https://github.com/xawei/learning
      revision: main
      files:
      - path: "argocd/myprj/base-components/**/*.yaml"
  template:
    metadata:
      name: '{{path.basenameNormalized}}-{{path[1]}}'  # Creates unique names like cert-manager-base-components
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/xawei/learning
        targetRevision: main
        path: '{{path.path}}'
        directory:
          include: '{{path.basename}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true        # ✅ Automatically remove resources not in Git
          selfHeal: true     # ✅ Automatically sync when Git changes
          allowEmpty: false  # ✅ Prevent accidental deletion of all apps
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground  # ✅ Ensure proper cleanup order
          - PruneLast=false                    # ✅ Prune first to clear stuck resources
          - Replace=true                       # ✅ Force replace stuck resources
          - ApplyOutOfSyncOnly=true           # ✅ Only apply what's out of sync
          - Delete=true                        # ✅ Allow deletion of applications
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m 