apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-pod-identity-agent
  labels:
    app.kubernetes.io/name: eks-pod-identity-agent
    app.kubernetes.io/component: agent
    app.kubernetes.io/version: v1.3.4
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"] 