apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
spec:
  source:
    helm:
      values: |
        # Cluster-specific configuration for kind-eksac-dev
        clusterName: kind-eksac-dev
        
        # Development-specific settings
        logLevel: debug
        
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi 