apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    chart: external-dns
    targetRevision: 1.15.0
    helm:
      values: |
        # External-DNS configuration for kind-eksac-dev cluster
        sources:
        - service
        - ingress
        
        # Provider configuration (for Kind, we'll use a dry-run mode)
        provider: 
          name: aws
        
        # Domain filtering - adjust as needed for your environment
        domainFilters:
        - eksac-dev.local
        
        # Registry for storing DNS record ownership info
        registry: txt
        txtOwnerId: kind-eksac-dev
        
        # Policy for creating DNS records
        policy: sync
        
        # Dry run mode for Kind cluster (safer for testing)
        dryRun: true
        
        # Deployment configuration
        replicaCount: 1
        
        # Resource limits
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          fsGroup: 65534
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        
        # Service account
        serviceAccount:
          create: true
          name: external-dns
        
        # RBAC
        rbac:
          create: true
        
        # Logging configuration
        logLevel: info
        logFormat: text
        
        # Interval for DNS updates
        interval: 1m
        
        # Metrics
        metrics:
          enabled: true
          port: 7979
        
        # Exclude specific namespaces
        excludeDomains:
        - cluster.local
        - local
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/progressDeadlineSeconds
    - /spec/revisionHistoryLimit
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/sessionAffinity 