apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the common base and include cluster-specific applications
resources:
  - ../../common
  - external-dns.yaml

# Patch cluster-specific values
patchesStrategicMerge:
  - aws-load-balancer-controller-patch.yaml 