apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.13.2
    helm:
      values: |
        # PLACEHOLDER - will be replaced by Kustomize patches
        clusterName: REPLACE_CLUSTER_NAME
        region: ap-southeast-1

        replicaCount: 1

        # Toleration for Karpenter infra nodepool
        tolerations:
        - key: "karpenter.sh/nodepool"
          operator: "Equal"
          value: "infra"
          effect: "NoSchedule"

        # Default configurations - can be overridden per cluster
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

        # Enable webhook
        enableCertManager: true

        # Default logging
        logLevel: info
        
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: aws-load-balancer-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 