apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  # Git file generator - reads cluster configurations
  - git:
      repoURL: https://github.com/xawei/learning
      revision: main
      files:
      - path: "argocd/myprj/clusters/**/cluster-config.yaml"
  template:
    metadata:
      name: 'aws-load-balancer-controller-{{cluster.name}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://aws.github.io/eks-charts
        chart: aws-load-balancer-controller
        targetRevision: 1.13.2
        helm:
          values: |
            clusterName: {{cluster.name}}
            region: {{cluster.region}}
            
            replicaCount: 1
            
            # Toleration for Karpenter infra nodepool
            tolerations:
            - key: "karpenter.sh/nodepool"
              operator: "Equal"
              value: "infra"
              effect: "NoSchedule"
              
            # Additional cluster-specific configurations
            {{#cluster.additionalValues}}
            {{.}}
            {{/cluster.additionalValues}}
      destination:
        server: '{{cluster.server}}'
        namespace: aws-load-balancer-controller
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m 