apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.18.2
    helm:
      values: |
        installCRDs: true
        
        # Toleration for Karpenter infra nodepool
        tolerations:
        - key: "karpenter.sh/nodepool"
          operator: "Equal"
          value: "infra"
          effect: "NoSchedule"
        
        webhook:
          port: 9443
          # Toleration for webhook pods
          tolerations:
          - key: "karpenter.sh/nodepool"
            operator: "Equal"
            value: "infra"
            effect: "NoSchedule"
        
        certController:
          requeueInterval: 20s
          # Toleration for cert controller pods
          tolerations:
          - key: "karpenter.sh/nodepool"
            operator: "Equal"
            value: "infra"
            effect: "NoSchedule"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true