# Default values for common-apps chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This value will be overridden by the root application
clusterName: "default-cluster"

# Velero Backup Configuration
velero:
  # -- Set to false to disable Velero installation
  enabled: true

  serviceAccount:
    # -- The ARN of the IAM role to associate with the Velero service account.
    # This will be overridden by the root application for each cluster.
    roleARN: "arn:aws:iam::ACCOUNT_ID:role/VeleroRole-Default"

  configuration:
    backupStorageLocation:
    - name: default
      provider: aws
      bucket: "YOUR_BUCKET_NAME"
      config:
        region: "YOUR_BUCKET_REGION"
    volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: "YOUR_BUCKET_REGION"

  # -- Velero plugins to install. For AWS, the aws plugin is required.
  # See: https://velero.io/docs/main/supported-providers/
  plugins:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.10.0 # Use a specific stable version

  # -- Tolerations for Velero pods to run on specific nodes
  tolerations:
  - key: "karpenter.sh/nodepool"
    operator: "Equal"
    value: "infra"

# AWS EBS CSI Driver Configuration
awsEbsCsiDriver:
  # -- Chart version compatible with Kubernetes 1.18+
  chartVersion: "2.37.0"
  
  serviceAccount:
    # -- The ARN of the IAM role to associate with the EBS CSI Driver service account.
    # This will be overridden by the root application for each cluster.
    roleARN: "arn:aws:iam::ACCOUNT_ID:role/EbsCsiDriverRole-Default"
  
  # -- Tolerations for EBS CSI Driver controller pods (not daemonset)
  tolerations:
  - key: "karpenter.sh/nodepool"
    operator: "Equal"
    value: "infra"
    effect: "NoSchedule"